### ISSUE TITLE
unique-ness of manifest tracking number

### ISSUE THREAD

**Issue by pkarman** [18F/e-manifest#53]
Currently the API allows for fetching, updating and signing a manifest using a user-supplied manifest tracking number, which is mapped in the manifest content as `generator.manifest_tracking_number`.

No unique-ness constraints are applied to `manifest_tracking_number` in the e-Manifest database.

What this means is that user can POST multiple manifests with identical `manifest_tracking_number` values. If a user does that, and then attempts to fetch, update or sign using `manifest_tracking_number` as a parameter, which manifest are they fetching, updating and/or signing?

Since we follow a generous policy of accepting all manifests with any `manifest_tracking_number` value, I propose that we disallow `manifest_tracking_number` for fetching, updating or signing.

**Comment by jessieay** [comment]
+1

**Comment by zacharycohn** [comment]
+1.

**Comment by scottdchristian** [comment]
Manifest Tracking Number is the lynch pin of the system and we have to allow for corrections.  I assume by " disallow manifest_tracking_number for fetching, updating or signing" you mean using "manifest_tracking_number" only.  

Since updating and retrieving are needs a user wishing to do this could 
1) retrieve all versions
2) retrieve a specific manifest ID field (as the demo was originally designed)
3) retrieve/ update/ sign the most recent 

FYI, Zac has heard this, but in rare cases there are duplicate manifest tracking numbers that are different sheets of paper and become different shipments.  Ideally this does not happen, but allegedly has.

A best practice may be to have industry first do a get manifest_tracking_number, then submit.

**Comment by jessieay** [comment]
based on convo in Slack, it seems that Scott agrees with the comments made by Pkarman above. For dealing with individual resources, let's reference manifests via a unique id.

But, per his comment in here, we also need some new endpoints related to manifest tracking number:
- GET all manifests for a manifest tracking number
- GET / PATCH most recent manifest for a tracking number
- POST /signature for most recent manifest by tracking number
- Have /search endpoint only show most recent manifest for each tracking #

**Comment by jessieay** [comment]
@scottdchristian please confirm my bullets above and let us know if there are any corrections

**Comment by pkarman** [comment]
I don't think `/search` should only show most recent. I think it should show exactly what matches the search. You can sort by `created_at` easily enough (which is exactly what a GET all manifests for a manifest tracking number would do).

**Comment by jessieay** [comment]
@pkarman agreed. Perhaps we could create a general index view to show most recent by tracking # per Scott's Slack comment:

> We plan on posting the most recent version to the public after 90 days and people probably want the most upto date data

**Comment by pkarman** [comment]
@jessieay I would be inclined to wait and see what users actually want, rather than guess what they probably want.

**Comment by zacharycohn** [comment]
Agree with @pkarman - search should not show only the most recent. If there is a duplicate, that's a problem and we want to surface that problem.

**Comment by jessieay** [comment]
@zacharycohn according to Scott, people might submit a manifest multiple times. So not necessarily problematic if there are multiple manifests for a single manifest tracking number. But we should confirm why that is the case, since it would be ideal for subsequent requests to PATCH a manifest rather then creating over and over.

**Comment by scottdchristian** [comment]
A reason for the 90 day period is so that a manifest can be finalized.  The last version is what should be posted and available for public to view.  See https://www.gpo.gov/fdsys/pkg/FR-2014-02-07/pdf/2014-01352.pdf
Companies, States, and individuals submitters (CROMERR) should be able to see all versions.  Rereading the rule, I would need to check to see if we could post all versions of the manifest

**Comment by scottdchristian** [comment]
What I suggested encompasses all ways a user would retrieve data.  Everything, single, most recent.  

@zacharycohn according to our site visits and state users a manifest may need to be updated, is this in question?  It should not be, corrections are a need.  They are a state need, EPA need, and Industry compliance need.

@jessieay @pkarman  I think I am starting to see what you are getting at. Currently with our manifest_tracking_number not being unique we are open to several issues.  We need to make manifest_tracking_number unique and handle the rare duplicate id case offline.  Seprately, we need to talk version control and the CDX archive.  Every signed version must exist in the CDX CROMERR archive.  Does every version need to exist in e-Manifest? 

Back to my best practice that a company should test the manifest ID number before submitting.  If we make it unique then we do not need to worry about that they'll get an instant reject message back we'll keep  a clean DB.

Thanks all,
Scott

**Comment by jessieay** [comment]
seems like this was resolved via convo and https://github.com/18F/e-manifest/pull/70
